### ISSUE TITLE
Full examples/doc would be useful

### ISSUE THREAD

**Issue by Yoric** [dropbox/rust-brotli#12]
I'm currently attempting to use this library and I admit that I am at a loss.

A full example of a command-line brotli encoder/decoder would be nice, for instance.

**Comment by danielrh** [comment]
src/bin/brotli.rs is a command line encoder... you could start with that and iterate

**Comment by danielrh** [comment]
Made some basic examples in https://github.com/dropbox/rust-brotli/tree/master/examples

**Comment by Yoric** [comment]
It's a start, thanks :)

I'm still very lost without documentation, with errors that show up only when the buffer size is too small/too large, etc. So more documentation on exactly *what* the buffer size is would be really, really useful.

**Comment by danielrh** [comment]
Hmm I didn't realize that buffer size resulted in errors. can you give a concrete example where a buffer size caused an error: it could be a bug (!)
generally the unix block size (4096) has always worked for me
