### ISSUE TITLE
Code should check that buffer-length is not 0

### ISSUE THREAD

**Issue by Yoric** [dropbox/rust-brotli#13]
After a few hours of debugging, I finally realized that I had accidentally passed a buffer length of 0 to the API. For some reason, this doesn't work :)

Since 0 is obviously not a valid value, could the code add an assertion to ensure that it's not 0?

**Comment by danielrh** [comment]
I played around with this a bit and I'm not sure it's obvious
I changed the compressor to error out when a 0 buffer is passed, and then one of my tests which passed the entire "data" buffer into compress failed when the data buffer was size 0.

Which API fails hard with zero? is it the streaming API? the Read or Write API's?
