### ISSUE TITLE
Overflow on 32bit target

### ISSUE THREAD

**Issue by dfrankland** [dropbox/rust-brotli#15]
I've been working on some WebAssembly projects using the `wasm32-unknown-unknown` target and I sometimes get a panic / abort.

To reproduce this issue, I made a small crate which one can use with `cargo run` and a target of `i686-unknown-linux-gnu` (this may fail to build on 64bit machines; I had to use a 32bit Ubuntu VM). Running that gives this error:

```
thread 'main' panicked at 'attempt to shift right with overflow', /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1131:34
```

**Cargo.toml**
```toml
[package]
name = "test-brotli-32bit-target"
version = "0.0.0"

[dependencies]
brotli = "1.1.0"
```

**main.rs**
```rust
extern crate brotli;

use brotli::{BrotliCompress, BrotliDecompress};
use brotli::enc::{BrotliEncoderInitParams};

fn main() {
    let mut input: &[u8] = b"
      <!doctype html>
      <html>
        <head>
          <title>Testing!</title>
        </head>
        <body>
          <h1>Hello, world!</h1>
        </body>
      </html>
    ";

    let mut compressed_input = vec![];
    let params = BrotliEncoderInitParams();
    BrotliCompress(&mut input, &mut compressed_input, &params).unwrap();

    let mut result = vec![];
    match BrotliDecompress(&mut compressed_input.as_slice(), &mut result) {
        Ok(_) => println!("Success! {:?}", result),
        Err(e) => println!("Error! {:?}", e),
    }
}
```

<details> 
  <summary>Here's the full Rust backtrace</summary>
  <pre>
    <code>
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/test-brotli-32bit-target`
thread 'main' panicked at 'attempt to shift right with overflow', /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1131:34
stack backtrace:
   0: 0x8012d18d - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h56cb4e8fab26ca56
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: 0x8012f603 - std::sys_common::backtrace::print::hdde3d983397ec5dc
                       at /checkout/src/libstd/sys_common/backtrace.rs:68
                       at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: 0x80129e96 - std::panicking::default_hook::{{closure}}::hf7f4c21e0cce9605
                       at /checkout/src/libstd/panicking.rs:381
   3: 0x80129aa6 - std::panicking::default_hook::h0273df4f31ad7ce9
                       at /checkout/src/libstd/panicking.rs:397
   4: 0x8012a245 - std::panicking::rust_panic_with_hook::hb110eb893cf2f262
                       at /checkout/src/libstd/panicking.rs:577
   5: 0x8012a10a - std::panicking::begin_panic::hba4f7483f98fa441
                       at /checkout/src/libstd/panicking.rs:538
   6: 0x8012a026 - std::panicking::begin_panic_fmt::hf4a59e9c0b17558b
                       at /checkout/src/libstd/panicking.rs:522
   7: 0x80129f9b - rust_begin_unwind
                       at /checkout/src/libstd/panicking.rs:498
   8: 0x8017728e - core::panicking::panic_fmt::h34d249fd2e4d796e
                       at /checkout/src/libcore/panicking.rs:71
   9: 0x8017717c - core::panicking::panic::h912f4f8254e1a3ab
                       at /checkout/src/libcore/panicking.rs:51
  10: 0x800f923c - brotli::enc::backward_references::TestStaticDictionaryItem::h8e3ceceaf96520b2
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1131
  11: 0x80042d3e - brotli::enc::backward_references::SearchInStaticDictionary::hbe772f9a65587fc3
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1171
  12: 0x80035f59 - <brotli::enc::backward_references::AdvHasher<Specialization, AllocU16, AllocU32> as brotli::enc::backward_references::AnyHasher>::FindLongestMatch::h0b8eb4ddd2cce0b7
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:997
  13: 0x8003e19c - brotli::enc::backward_references::CreateBackwardReferences::he3119ac7c3437ed4
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1348
  14: 0x8004458d - brotli::enc::backward_references::BrotliCreateBackwardReferences::h4ce86d42244db8fa
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/backward_references.rs:1535
  15: 0x80087f11 - brotli::enc::encode::EncodeData::h2155e11331a85a0b
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/encode.rs:2799
  16: 0x800907c1 - brotli::enc::encode::BrotliEncoderCompressStream::hc8b4e371187e8bca
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/encode.rs:3366
  17: 0x800b082d - brotli::enc::BrotliCompressCustomIo::hbb4c34f675cafcbe
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/mod.rs:240
  18: 0x800b12c3 - brotli::enc::BrotliCompressCustomAlloc::h2dfef9c4c5059e19
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/mod.rs:138
  19: 0x800b0184 - brotli::enc::BrotliCompress::he08961ea1a50f683
                       at /home/osboxes/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.0/src/enc/mod.rs:65
  20: 0x800e831f - test_brotli_32bit_target::main::hf8054a0ec07e1298
                       at src/main.rs:21
  21: 0x800e8212 - std::rt::lang_start::{{closure}}::he8b899603e478150
                       at /checkout/src/libstd/rt.rs:74
  22: 0x8012f97c - std::sys_common::backtrace::__rust_begin_short_backtrace::h72d10003122a0a61
                       at /checkout/src/libstd/rt.rs:59
                       at /checkout/src/libstd/sys_common/backtrace.rs:133
  23: 0x80129f52 - std::panicking::try::do_call::hb55332b2ef16d564
                       at /checkout/src/libstd/rt.rs:59
                       at /checkout/src/libstd/panicking.rs:480
  24: 0x8013d2d2 - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:101
  25: 0x8012cf65 - std::rt::lang_start_internal::h2cf06419fef56d5f
                       at /checkout/src/libstd/panicking.rs:459
                       at /checkout/src/libstd/panic.rs:365
                       at /checkout/src/libstd/rt.rs:58
  26: 0x800e81e1 - std::rt::lang_start::h2e896fbd6e6fa04c
                       at /checkout/src/libstd/rt.rs:74
  27: 0x800e878a - main
  28: 0xb758f275 - __libc_start_main
  29: 0x80010c4d - <unknown>
    </code>
  </pre>
</details>

**Comment by danielrh** [comment]
Can you verify this fixes your issue--the code in the encoder was definitely platform-specific and assumed a 64 bit usize. This has been (hopefully) corrected--and I looked for other possible u64/usize ambiguities that could crop up on large files-- and I believe they are all solved

**Comment by dfrankland** [comment]
@danielrh, you rock! I've tested this out on my 32-bit Ubuntu VM and on [wasm-brotli](https://github.com/dfrankland/wasm-brotli) and everything seems to work out 👍
