### ISSUE TITLE
impl Default for BrotliEncoderParams and documentation of the parameters

### ISSUE THREAD

**Issue by Martin1887** [dropbox/rust-brotli#16]
Hello.

I'm using this library and I have noticed that the struct BrotliEncoderParams has many and not documented fields.

It would nice having a new method or a Default implementation for this struct with sane defaults.

For instance, quality 1 and lgwin 22 are the values I am using, and they provide a fast compression with the recommended value for the window size. There are many other attributes and I am slightly lost however.

Updating the README should be also desirable, since the BrotliCompress method receives quality and lgwin as parameters instead BrotliEncoderParams in the README. I have noticed it because a compilation error, and I have needed navigating into the source code to find the correct BrotliCompress signature.

Thanks and regards.

**Comment by Martin1887** [comment]
I have discovered the function brotli::enc::BrotliEncoderInitParams(), but updating README and implementing the standard Default trait remains being desirable.

Thanks and regards.

**Comment by danielrh** [comment]
Added default() in version 2.0.0
