### ISSUE TITLE
`flush()` is unexpectedly panicking

### ISSUE THREAD

**Issue by mbr** [dropbox/rust-brotli#20]
The following program panics on Rust 1.26.1 using brotli 2.2.1:

```Rust
extern crate brotli;

use std::io::{self, Write};

fn main() {
    let stdout = &mut io::stdout();
    let mut writer = brotli::CompressorWriter::new(stdout, 4096, 5, 22);
    let data = b"0123456789";

    writer.write_all(data).unwrap();
    writer.flush().unwrap();

    // the next write will panic
    writer.write_all(data).unwrap();
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: StringError("Invalid Data") }', libcore/result.rs:945:5
```

I am not sure whether or not there is a fix for this; I do not know enough about the brotli internals (compression algorithm or crate), but the flush behavior is very confusing. Barring an actual output failure, I would assume that most users will not associate `flush()` after a successful `write_all()` with a likely panic.

Any use of `CompressorWriter::flush()` as implemented right now could probably be replaced with `mem::drop`, which would be better as it prevents a panic from calling `write_all()` again at compile time.

If the codec does not allow partial flushing, I believe `flush()` should be a no-op. On the other hand, if it possible, I would very much like to use it in my use-case, which is streaming packets over TCP, flushing at each packet boundary to ensure they arrive in a timely manner.

**Comment by danielrh** [comment]
Thanks for the bug report! I just fixed it in version 2.3 , in commit c1959aeca4e6deda8021a2a5bcc5ebac753dd599 ,  currently at crates.io!
