### ISSUE TITLE
Panic when compression quality level is exactly `10`

### ISSUE THREAD

**Issue by marvinhagemeister** [dropbox/rust-brotli#216]
It looks like there is a panic when the quality level is set to exactly `10`. This is caused by this check:

https://github.com/dropbox/rust-brotli/blob/37d403b437c3cbd1c686871a4167290aab401704/src/enc/encode.rs#L1468-L1470

I went through the git history, but I'm not sure why it was added.

Discovered in https://github.com/denoland/deno/issues/24572

**Comment by danielrh** [comment]
does the system work well without the check? have you validated it? Can we simply remove the assert?

**Comment by marvinhagemeister** [comment]
For now we went with a workaround and changed `10` to `9.5` if we encounter it https://github.com/denoland/deno/blob/37cedefb4dc4f582311d7478d414d59469e4af5e/ext/node/polyfills/_brotli.js#L137-L142

```rs
  // NOTE(bartlomieju): currently the rust-brotli crate panics if the quality
  // is set to 10. Coerce it down to 9.5 which is the maximum supported value.
  // https://github.com/dropbox/rust-brotli/issues/216
  if (quality == 10) {
    quality = 9.5;
  }
```

**Comment by danielrh** [comment]
ok fixed!
