### ISSUE TITLE
Uploaded source code contains binary data

### ISSUE THREAD

**Issue by weiznich** [dropbox/rust-brotli#220]
While looking through the changes of a recent update of the brotli crate I noticed that the source code uploaded to crates.io contains the binary test data: https://diff.rs/brotli/6.0.0/7.0.0/testdata

Given the recent xz incident that might not be desirable as it makes it harder to review what's going on inside the binary data. Additionally these data add unneeded bloat to the source code.

**Comment by danielrh** [comment]
We are a standardized format. These files are bit-for-bit identical with https://github.com/google/brotli and people can validate they don't just change on a whim. If we deleted these files how could we assert backwards compatibility.
We need the files. They serve a purpose. Binary doesn't mean scary--they are also human readable if you read the spec.
