### ISSUE TITLE
Provide Rust only interface

### ISSUE THREAD

**Issue by Nemo157** [dropbox/rust-brotli#46]
Having the C FFI interface exported via `no_mangle` functions when `brotli` is used as an `rlib` dependency causes issues when linking into a project that also depends on the C `brotli` library (see https://github.com/Nemo157/async-compression/issues/83).

I'm not sure what the best approach for this would be; as someone that has not worked on a library exposing a C ABI, it seems to me that this would work better as a separate crate simply wrapping a Rustic implementation, instead of being combined into a single crate. Another idea I had was putting the `ffi` module behind a cargo feature. But neither of these feel like the perfect solution to me.

**Comment by danielrh** [comment]
wow I never imagined the compatibility would cause issues... I wonder if feature flag is the  best... we can set it on by default?
Mind authoring a patch for it?

**Comment by Nemo157** [comment]
Yep, I can take a look.
