### ISSUE TITLE
simd feature doesn't compile

### ISSUE THREAD

**Issue by ZettaScript** [dropbox/rust-brotli#59]
## Problem
The `simd` feature doesn't compile because of an error in `packed_simd`.

## Steps to reproduce
Add dependency `brotli` with `simd` feature to any crate.

## Solution
Switching to [`packed_simd_2`](https://crates.io/crates/packed_simd_2) is probably the solution.

## Details
Tested with Rust stable 1.54.0 and nightly 1.56.0 (2021-07-28), on Linux 5.10.52-1-lts.

**Comment by ZettaScript** [comment]
I tried `packed_simd_2`, it compiles and runs fine.

In fact it looks like the feature doesn't change anything.

**Comment by billyb2** [comment]
You may be interested in #62

**Comment by atouchet** [comment]
This crate is now using packed_simd_2 as of #62. Can this be closed now?
