### ISSUE TITLE
Consider making dictionary values static

### ISSUE THREAD

**Issue by jdm** [dropbox/rust-brotli#6]
All the values in src/dictionary/mod.rs are currently marked `const`, and this looks like it could hurt the code that uses them. Const values are inlined in every use, whereas static values have a single global location in memory.

Reference: https://doc.rust-lang.org/book/const-and-static.html

**Comment by danielrh** [comment]
wow nice find...will update and benchmark

**Comment by danielrh** [comment]
yup it helps!
