### ISSUE TITLE
Size of published crate could be smaller

### ISSUE THREAD

**Issue by retep998** [dropbox/rust-brotli#8]
`src/bin/testdata` is over 18MB and entirely useless in the published crate since people don't get crates off of crates.io in order to run its tests.
I also found no references to the `corrosion` folder in the source code, which leads me to think it is also dead weight taking up another 26MB of space which isn't needed in the published crate.
Granted the actual space taken up in the `.crate` that people download from crates.io is less due to compression, but that's still quite a lot of savings.

**Comment by danielrh** [comment]
so you'd recommend using the exclude field?

I'm going to do a sizable rev to the library soon--so I'll incorporate this suggestion at that time... probably will get rid of the entire corrosion folder
