### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by xfbs** [dropbox/rust-brotli#90]
Hey team,

first of all, awesome work! I don't know if this is a bug or accidental, but there's some code style issues with the crate, these functions use CamelCase rather than underscore_case as functions should in Rust (to distinguish them from type names, such as structs, enums, and traits):
- [BrotliDecompress](https://docs.rs/brotli/latest/brotli/fn.BrotliDecompress.html)
- [BrotliDecompressCustomAlloc](https://docs.rs/brotli/latest/brotli/fn.BrotliDecompressCustomAlloc.html)
- [BrotliDecompressCustomIo](https://docs.rs/brotli/latest/brotli/fn.BrotliDecompressCustomIo.html)
- [BrotliDecompressCustomIoCustomDict](https://docs.rs/brotli/latest/brotli/fn.BrotliDecompressCustomIoCustomDict.html)
- [BrotliDecompressStream](https://docs.rs/brotli/latest/brotli/fn.BrotliDecompressStream.html)
- [TransformDictionaryWord](https://docs.rs/brotli/latest/brotli/fn.TransformDictionaryWord.html)

Is this intentional or would it be possible to fix it for an upcoming major release? I understand if it is a deliberate design choice, but it would fit in better with the Rust ecosystem if these matched the established style.

Also, in general I notice that the code base seems to be in desperate need of some "cargo fmt". Is this something that is intentionally not done? 

Thanks for the great work,
-Patrick

**Comment by danielrh** [comment]
Much of the code was translated from google's C brotli system. We wanted to keep function names aligned.
